# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source "https://rubygems.org/"


gem "bundler", "~>1.16.0", :group => [:development, :test]
gem "hoe", "~>3.1", :group => [:development, :test]
gem "hoe-bundler", ">=0", :group => [:development, :test]
gem "hoe-gemspec", ">=0", :group => [:development, :test]
gem "hoe-git", ">=0", :group => [:development, :test]
gem "rake-compiler", ">=0", :group => [:development, :test]
gem "rspec", "~>3.5.0", :group => [:development, :test]
gem "concourse", "~>0.1", :group => [:development, :test]
gem "rdoc", "~>4.0", :group => [:development, :test]

# vim: syntax=ruby
