resources:
  - name: ci
    type: git
    source:
      uri: https://github.com/jbarnette/hoe-debugging/
      branch: master
      disable_ci_skip: true # always get the latest pipeline configuration

  - name: hoe-debugging
    type: git
    source:
      uri: https://github.com/jbarnette/hoe-debugging/
      branch: master
      ignore_paths:
        - concourse/**

jobs:
% (RUBIES[:mri].last(2) + RUBIES[:mri].first(1)).each do |ruby_version|
  - name: "ruby-<%= ruby_version %>"
    public: true
    plan:
      - get: ci
      - get: hoe-debugging
        trigger: true
      - task: rake-test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: ruby, tag: "<%= ruby_version %>"}
          inputs:
            - name: ci
            - name: hoe-debugging
          run:
            path: ci/concourse/tasks/rake-test/task.sh
% end
